- name: demo on loops
  hosts: all
  connection: local
  tasks:
    - name: fruit names
      ansible.builtin.debug:
        msg: fruit name is {{item}}
      loop:
        - apple
        - banana
        - grape