- name: demo on conditions
  hosts: all
  connection: local
  vars:
    a: 100
    b: true
  tasks:
    - name: string conditions
      debug:
        msg: fruit name is apple
      when: fruit_name == "apple"
    - name: numerical coditions
      debug:
        msg: a is greater then 10
      when: a > 10
    - name: boolean condtions
      debug:
        msg: b is true
      when: b