- name: demo on parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: getting parameter from aws parameter store
      ansible.builtin.debug:
        msg: "{{ lookup('aws_ssm', 'test', region='us-east-1' ) }}"